/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	char name[256];
	char path[256];
	int a;
	int b;
};
typedef struct numbers numbers;

#define PART_B_PROG 0x11111111
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define blackbox 1
extern  char ** blackbox_1(numbers *, CLIENT *);
extern  char ** blackbox_1_svc(numbers *, struct svc_req *);
extern int part_b_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define blackbox 1
extern  char ** blackbox_1();
extern  char ** blackbox_1_svc();
extern int part_b_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
